[package]
name = "jedi/street"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7.0"
Input = "sleitnick/input@2.3.0"
Signal = "sleitnick/signal@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
Timer = "sleitnick/timer@1.1.2"
WaitFor = "sleitnick/wait-for@1.0.0"
Option = "sleitnick/option@1.0.5"
Component = "sleitnick/component@2.4.8"
Shake = "sleitnick/shake@1.1.0"
Symbol = "sleitnick/symbol@2.0.1"
Streamable = "sleitnick/streamable@1.2.4"
Trove = "sleitnick/trove@1.3.0"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
Janitor = "howmanysmall/janitor@1.16.0"
ProfileService = "nidoxs/profileservice@1.0.0"
KeyForm = "ffrostflame/keyform@0.2.2"
